# yaml-language-server: $schema=https://raw.githubusercontent.com/mui/toolpad/v0.11.0/docs/schemas/v1/definitions.json#properties/Page

apiVersion: v1
kind: page
spec:
  alias:
    - nxOIZvJ
  title: Default page
  content:
    - component: Text
      name: textAjouterUnLivre
      props:
        value: Ajouter un livre
        variant: h3
      layout:
        horizontalAlign: center
    - component: TextField
      name: AjouterTitre
      props:
        label: Titre
        isRequired: true
    - component: TextField
      name: AjouterAuteur
      props:
        label: Auteur
        isRequired: true
    - component: TextField
      name: AjouterIsbn
      props:
        label: ISBN
        isRequired: true
    - component: TextField
      name: AjouterDescription
      props:
        label: Description
        fullWidth: true
    - component: Checkbox
      name: AjouterDisponible
      props:
        mode: checkbox
        label: Disponible
        disabled: false
    - component: Button
      name: ButtonAjouter
      props:
        content: Ajouter a la bibliotheque
        disabled:
          $$jsExpression:
            AjouterTitre.value ==""  || AjouterAuteur.value == "" ||
            AjouterIsbn.value == ""
        onClick:
          $$jsExpressionAction: AjouterLivre.call()
    - component: Text
      name: textListeDeLivre
      props:
        value: Liste des livres
        variant: h4
      layout:
        horizontalAlign: center
    - component: Button
      name: buttonRafraichir
      props:
        content: Rafraichir la liste
        onClick:
          $$jsExpressionAction: GetLivres.refetch()
    - component: Checkbox
      name: checkboxAfficherTousLesLivres
      props:
        mode: checkBox
        label: Tous
        color: primary
        size: medium
        fullWidth: false
      layout:
        horizontalAlign: end
    - component: DataGrid
      name: ListeDeLivre
      props:
        rows:
          $$jsExpression: GetLivres.data.livres
        columns:
          - field: titre
            type: string
            width: 182.9971466064453
          - field: auteur
            type: string
            width: 173.9943084716797
          - field: isbn
            type: string
            width: 162
          - field: description
            type: string
            width: 317.9630432128906
          - field: disponible
            type: boolean
            width: 159.99432373046875
        density: standard
        hideToolbar: false
        loading: false
    - component: Button
      name: buttonSupprimerLivre
      props:
        content: Supprimer le livre
        disabled:
          $$jsExpression: ListeDeLivre.selection == null
        onClick:
          $$jsExpressionAction: SupprimerLivre.call()
    - component: Button
      name: buttonDetails
      props:
        content: VOIR LES DETAILS
        onClick:
          $$jsExpressionAction: GetDetailsLivre.call()
        disabled:
          $$jsExpression: ListeDeLivre.selection == null
    - component: Text
      name: textDetailLivre
      props:
        value: Details du livre
        variant: h4
      layout:
        horizontalAlign: center
    - component: TextField
      name: TitreLivre
      props:
        label: Titre
        defaultValue:
          $$jsExpression: GetDetailsLivre.data.detail.titre
    - component: TextField
      name: AuteurLivre
      props:
        label: Auteur
        defaultValue:
          $$jsExpression: GetDetailsLivre.data.detail.auteur
    - component: TextField
      name: IsbnLivre
      props:
        label: ISBN
        defaultValue:
          $$jsExpression: GetDetailsLivre.data.detail.isbn
    - component: TextField
      name: DescriptionLivre
      props:
        label: Description
        defaultValue:
          $$jsExpression: GetDetailsLivre.data.detail.description
        fullWidth: true
    - component: TextField
      name: DateAjout
      props:
        label: Date Ajout
        defaultValue:
          $$jsExpression: new
            Date(GetDetailsLivre.data.detail.date_ajout).toLocaleDateString('fr-CA')
        disabled: true
    - component: TextField
      name: DateModification
      props:
        label: Date Modification
        defaultValue:
          $$jsExpression: new
            Date(GetDetailsLivre.data.detail.date_modification).toLocaleDateString('fr-CA')
        disabled: true
    - component: TextField
      name: Disponible
      props:
        disabled: true
        label: Statut
        defaultValue:
          $$jsExpression:
            "GetDetailsLivre.data.detail.disponible ? 'disponible' :
            'indisponible'"
    - component: Button
      name: buttonModifierLivre
      props:
        content: Modifier le livre
        onClick:
          $$jsExpressionAction: ModifierLivre.call()
        disabled:
          $$jsExpression: ListeDeLivre.selection == null
    - component: Checkbox
      name: CheckboxStatutLivre
      props:
        mode: checkBox
        label: Statut du livre
    - component: Button
      name: buttonModifierStatut
      props:
        content: Modifeir le statut
        disabled:
          $$jsExpression: ListeDeLivre.selection == undefined
        onClick:
          $$jsExpressionAction: ModifierStatutLivre.call()
    - component: DataGrid
      name: ListePrets
      props:
        rows:
          $$jsExpression: "GetDetailsLivre.data == null ? [] : GetDetailsLivre.data.prets"
        columns:
          - field: id
            type: number
            width: 52
          - field: emprunteur
            type: string
            width: 254.00000762939453
          - field: date_debut
            type: dateTime
            width: 235.00000762939453
          - field: date_retour_prevue
            type: dateTime
            width: 245.00000762939453
          - field: date_retour
            type: dateTime
            width: 226.00000762939453
          - field: statut
            type: string
            width: 144.00000762939453
  queries:
    - name: GetLivres
      mode: query
      query:
        kind: rest
        url:
          $$jsExpression:
            "`${parameters.API_HOST}/api/bibliotheque/livres/liste?tous=${p\
            arameters.tous}`"
        headers:
          - name: Authorization
            value:
              $$jsExpression: "`${parameters.API_KEY}`"
        method: GET
        searchParams: []
      parameters:
        - name: API_HOST
          value:
            $$env: TOOLPAD_API_HOST
        - name: API_KEY
          value:
            $$env: TOOLPAD_API_KEY
        - name: tous
          value:
            $$jsExpression: "checkboxAfficherTousLesLivres.checked ? '1' : '0'"
    - name: GetDetailsLivre
      mode: mutation
      query:
        kind: rest
        url:
          $$jsExpression:
            "`${parameters.API_HOST}/api/bibliotheque/livres/${parameters.l\
            ivreId}`"
        headers:
          [
            {
              name: Authorization,
              value: { $$jsExpression: parameters.API_KEY },
            },
          ]
        method: GET
        searchParams: []
      parameters:
        - name: API_HOST
          value:
            $$env: TOOLPAD_API_HOST
        - name: API_KEY
          value:
            $$env: TOOLPAD_API_KEY
        - name: livreId
          value:
            $$jsExpression: ListeDeLivre.selection.id
    - name: AjouterLivre
      mode: mutation
      query:
        kind: rest
        url:
          $$jsExpression: "`${parameters.API_HOST}/api/bibliotheque/livres`"
        headers:
          - name: Authorization
            value:
              $$jsExpression: "`${parameters.API_KEY}`"
        method: POST
        body:
          kind: raw
          content:
            $$jsExpression: "JSON.stringify({\r

              \  \"titre\": parameters.titre,\r

              \  \"auteur\": parameters.auteur,\r

              \  \"isbn\": parameters.isbn,\r

              \  \"description\": parameters.description || null,\r

              \  \"disponible\": parameters.disponible ?? true\r

              })"
          contentType: application/json
        searchParams: []
      parameters:
        - name: API_HOST
          value:
            $$env: TOOLPAD_API_HOST
        - name: API_KEY
          value:
            $$env: TOOLPAD_API_KEY
        - name: titre
          value:
            $$jsExpression: AjouterTitre.value
        - name: isbn
          value:
            $$jsExpression: AjouterIsbn.value
        - name: auteur
          value:
            $$jsExpression: AjouterAuteur.value
        - name: description
          value:
            $$jsExpression: AjouterDescription.value
        - name: disponible
          value:
            $$jsExpression: AjouterDisponible.checked
    - name: ModifierLivre
      mode: mutation
      query:
        kind: rest
        url:
          $$jsExpression:
            "`${parameters.API_HOST}/api/bibliotheque/livres/${parameters.l\
            ivreId}`"
        headers:
          [
            {
              name: Authorization,
              value: { $$jsExpression: parameters.API_KEY },
            },
          ]
        method: PUT
        body:
          kind: raw
          content:
            $$jsExpression: "JSON.stringify({\r

              \  \"titre\": parameters.titre,\r

              \  \"auteur\": parameters.auteur,\r

              \  \"isbn\": parameters.isbn,\r

              \  \"description\": parameters.description || null\r

              })"
          contentType: application/json
        searchParams: []
      parameters:
        - name: titre
          value:
            $$jsExpression: TitreLivre.value
        - name: auteur
          value:
            $$jsExpression: AuteurLivre.value
        - name: isbn
          value:
            $$jsExpression: IsbnLivre.value
        - name: description
          value:
            $$jsExpression: DescriptionLivre.value
        - name: livreId
          value:
            $$jsExpression: ListeDeLivre.selection.id
        - name: API_HOST
          value:
            $$env: TOOLPAD_API_HOST
        - name: API_KEY
          value:
            $$env: TOOLPAD_API_KEY
    - name: ModifierStatutLivre
      mode: mutation
      query:
        kind: rest
        url:
          $$jsExpression:
            "`${parameters.API_HOST}/api/bibliotheque/livres/${parameters.l\
            ivreId}`"
        headers:
          - name: Authorization
            value:
              $$jsExpression: parameters.API_KEY
        method: PATCH
        searchParams: []
        body:
          kind: raw
          content:
            $$jsExpression: "JSON.stringify({\r

              \  \"disponible\": parameters.statut\r

              })"
          contentType: application/json
      parameters:
        - name: livreId
          value:
            $$jsExpression: ListeDeLivre.selection.id
        - name: statut
          value:
            $$jsExpression: CheckboxStatutLivre.checked
        - name: API_HOST
          value:
            $$env: TOOLPAD_API_HOST
        - name: API_KEY
          value:
            $$env: TOOLPAD_API_KEY
    - name: SupprimerLivre
      mode: mutation
      query:
        kind: rest
        url:
          $$jsExpression:
            "`${parameters.API_HOST}/api/bibliotheque/livres/${parameters.l\
            ivreId}`"
        headers:
          - name: Authorization
            value:
              $$jsExpression: parameters.API_KEY
        method: DELETE
        searchParams: []
      parameters:
        - name: livreId
          value:
            $$jsExpression: ListeDeLivre.selection.id
        - name: API_HOST
          value:
            $$env: TOOLPAD_API_HOST
        - name: API_KEY
          value:
            $$env: TOOLPAD_API_KEY
